In [1]:
import torch
import torch.nn.functional as F

In [2]:
logits = torch.rand(3, 2, 1)
print(logits)

tensor([[[0.0787],
         [0.8890]],

        [[0.9769],
         [0.3231]],

        [[0.6561],
         [0.5748]]])


In [3]:
logits = logits.repeat(1,1,2)
logits[:,:,0] = 1 - logits[:,:,0] 
print(logits)

tensor([[[0.9213, 0.0787],
         [0.1110, 0.8890]],

        [[0.0231, 0.9769],
         [0.6769, 0.3231]],

        [[0.3439, 0.6561],
         [0.4252, 0.5748]]])


In [4]:
# Sample soft categorical using reparametrization trick:
F.gumbel_softmax(logits, tau=0.5, hard=False)

tensor([[[7.2879e-01, 2.7121e-01],
         [1.9373e-01, 8.0627e-01]],

        [[7.0534e-04, 9.9929e-01],
         [9.9942e-01, 5.7516e-04]],

        [[9.1720e-01, 8.2796e-02],
         [4.5273e-04, 9.9955e-01]]])

In [5]:
# Sample soft categorical using reparametrization trick:
F.gumbel_softmax(logits, tau=1, hard=False)

tensor([[[0.3862, 0.6138],
         [0.3024, 0.6976]],

        [[0.3450, 0.6550],
         [0.6728, 0.3272]],

        [[0.4087, 0.5913],
         [0.5312, 0.4688]]])

In [6]:
# Sample hard categorical using "Straight-through" trick:
F.gumbel_softmax(logits, tau=1, hard=True)

tensor([[[0., 1.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]]])

In [7]:
# Sample hard categorical using "Straight-through" trick:
F.gumbel_softmax(logits, tau=1, hard=True)

tensor([[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [1., 0.]],

        [[1., 0.],
         [0., 1.]]])